version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - mongodb
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
      RAILS_ENV: development
    ports:
      - "3000:3000"

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:4.4.1
    restart: always
    volumes:
      - ./tmp/data/mongo/data:/data/db
    ports:
      - '27017:27017'

volumes:
  gem_cache:
  node_modules:
  db_data:
