default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: igti_attendances_simulator_development

test:
  <<: *default
  database: igti_attendances_simulator_test

production:
  <<: *default
